### ISSUE TITLE
AttributeError: 'GPTJConfig' object has no attribute 'suppress_tokens'

### ISSUE THREAD

**Issue by tin2tin** [robgon-art/GreenLIT#2]
Fascinating project. I'm getting an error: 
![image](https://user-images.githubusercontent.com/1322593/201512802-2523d5d6-bb5a-4802-bcec-8a27840a1978.png)

**Comment by robgon-art** [comment]
Hello, thanks for bringing this to my attention.

Please try back-revving transformers and bits and bytes, like this:

!pip install transformers==4.22.2
!pip install bitsandbytes==0.34.0
!pip install wikipedia

This should probably fix the issue.

**Comment by robgon-art** [comment]
I made this change and tested it. It seems to be fixed.

**Comment by tin2tin** [comment]
Thank you. Looks like I'll have to wait till tomorrow to test it: 
![image](https://user-images.githubusercontent.com/1322593/201540398-fe6428f9-2e24-4620-8029-9dc033c40bec.png)

![image](https://user-images.githubusercontent.com/1322593/201540468-c9bba96b-8c63-44b6-b35a-e6b022d4ad12.png)

**Comment by tin2tin** [comment]
Unfortunately, I'm still getting the same error:

![image](https://user-images.githubusercontent.com/1322593/204126311-7373feea-f595-4b94-8a1a-e5277c947d70.png)

![image](https://user-images.githubusercontent.com/1322593/204126511-c3b6f6de-4825-4e4e-8f7b-0a76c4b7c47d.png)

**Comment by robgon-art** [comment]
OK, I changed the Colab to use a newer version of the gdown downloader.
Please try again to see if this works now.

**Comment by tin2tin** [comment]
Yes, it is working now. Very Cool.

**Comment by robgon-art** [comment]
Great, thanks!
